[package]
name = "speed_daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
serde = { version = "1.0.217", features = ["derive"] }
bincode = "1.3.3"
tokio = { version = "1.43.0", features = ["sync"] }
